# Generated by Django 4.0.6 on 2023-02-03 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('attachment', models.FileField(upload_to='attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='EmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='EmailTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSent', models.DateField(default=django.utils.timezone.now)),
                ('unread', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.email')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailgroup')),
            ],
        ),
        migrations.CreateModel(
            name='EmailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
                ('avi', models.ImageField(null=True, upload_to='userImages/')),
            ],
        ),
        migrations.CreateModel(
            name='UserEmailGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
            ],
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
                ('spammer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
            ],
        ),
        migrations.CreateModel(
            name='Junk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
                ('junker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
                ('favoriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
            ],
        ),
        migrations.AddField(
            model_name='emailtransfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='dre_mail_api.emailuser'),
        ),
        migrations.AddField(
            model_name='emailtransfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dre_mail_api.emailuser'),
        ),
        migrations.CreateModel(
            name='Drafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drafter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
            ],
        ),
        migrations.CreateModel(
            name='DeletedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailuser')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
            ],
        ),
    ]
