# Generated by Django 4.1.6 on 2023-02-07 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dre_mail_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafts',
            name='emailTransfer',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='password',
        ),
        migrations.AddField(
            model_name='drafts',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailuser',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailgroup'),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='dre_mail_api.emailuser'),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='avi',
            field=models.ImageField(blank=True, null=True, upload_to='userImages/'),
        ),
    ]
