# Generated by Django 4.0.6 on 2023-02-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drafts',
            name='emailTransfer',
        ),
        migrations.AddField(
            model_name='drafts',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.email'),
            preserve_default=False,
        ),
    ]
