# Generated by Django 4.0.6 on 2023-02-03 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dre_mail_api', '0002_remove_drafts_emailtransfer_drafts_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='emailuser',
            name='password',
        ),
        migrations.AddField(
            model_name='emailuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='description',
            field=models.TextField(),
        ),
    ]
