# Generated by Django 4.1.6 on 2023-02-11 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0002_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailTransfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailtransfer')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
