# Generated by Django 4.1.6 on 2023-02-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0002_remove_drafts_emailtransfer_remove_emailuser_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEmailGroup',
            new_name='EmailGroupMembers',
        ),
    ]
