# Generated by Django 4.1.6 on 2023-02-11 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0003_emailreadstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtransfer',
            old_name='unread',
            new_name='read',
        ),
    ]
