# Generated by Django 4.1.6 on 2023-02-08 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0003_rename_useremailgroup_emailgroupmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='dre_mail_api.emailuser'),
            preserve_default=False,
        ),
    ]
