# Generated by Django 4.0.6 on 2023-02-03 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dre_mail_api', '0003_remove_emailuser_email_remove_emailuser_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
