# Generated by Django 4.1.6 on 2023-02-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0004_alter_emailuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtransfer',
            name='unread',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='avi',
            field=models.ImageField(blank=True, null=True, upload_to='userImages/'),
        ),
    ]
