# Generated by Django 4.1.6 on 2023-02-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0004_emailgroup_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailgroup',
            name='members',
            field=models.ManyToManyField(related_name='members', to='dre_mail_api.emailuser'),
        ),
        migrations.AlterField(
            model_name='emailgroup',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
