# Generated by Django 4.1.6 on 2023-02-11 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0004_rename_unread_emailtransfer_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtransfer',
            name='read',
        ),
        migrations.AddField(
            model_name='emailtransfer',
            name='hasRead',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EmailReadStatus',
        ),
    ]
