# Generated by Django 4.1.6 on 2023-02-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0005_alter_emailtransfer_unread_alter_emailuser_avi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtransfer',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailgroup'),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='dre_mail_api.emailuser'),
        ),
    ]
