# Generated by Django 4.1.6 on 2023-02-11 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0005_remove_emailtransfer_read_emailtransfer_hasread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtransfer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dre_mail_api.emailgroup'),
        ),
        migrations.AlterField(
            model_name='emailtransfer',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
