# Generated by Django 4.1.6 on 2023-02-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0005_emailgroup_members_alter_emailgroup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailGroupMembers',
        ),
    ]
