# Generated by Django 4.1.6 on 2023-02-07 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dre_mail_api', '0006_alter_emailtransfer_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtransfer',
            name='dateSent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
